[project]
name = "simplefastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.121.3",
    "passlib>=1.7.4",
    "pyjwt>=2.10.1",
    "sqlmodel",
]
